name: Finish Upgrade Mode

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  remove-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - run: |
          echo 'null' > src/public/attestation.json


      - name: Remove the attestation file and create a PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "disable upgrade mode by removing the contents of the published attestation.json"
          title: "Disable Upgrade Mode"
          body: "This PR finishes the system-wide upgrade mode by removing the contents of the published attestation.json"
          add-paths: |
              src/public/attestation.json